#########################################################################
# Name        : crt_spongebob_mku.yml
# Creator     : L.S.H.
# Syntax      : None, just be called by main playbook 
# Description : Make up VM on Azure & Be included from crt_spongebob.yml
#########################################################################
---
####################################
# hostname change 
####################################
- name: "Change host name"
  hostname:
    name: "{{ inventory_hostname_short }}"

####################################
# ntp setup
####################################
- name: "NTP install"
  yum:
    name: ntp
    state: latest

- name: "Set ntp.conf"
  template:
    src: /etc/ansible/template/ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644

- name: "regist auto start"
  service:
    name: ntpd
    enabled: yes

- name: start ntp
  service:
    name: ntpd
    state: restarted

####################################
# timezone setup
####################################
- name: "TimeZone setup"
  timezone:
    name: Asia/Seoul
    
####################################
# selinux disable
####################################
- name: Disable SELinux
  selinux:
    state: disabled

####################################
# firewalld disable
####################################
- name: Disable firesalld
  service:
    name: firewalld
    state: stopped
    enabled: False

####################################
# swap disable
####################################
- name: Disable swap
  shell: |
    sudo sed -i '/swap/d' /etc/fstab
    sudo swapoff -a

####################################
# jdk install 
####################################
- name: "JDK install"
  yum:
    name: java-1.8.0-openjdk
    state: latest

