##############################################################################
# Name        : crt_spongebob.yml
# Creator     : L.S.H.
# Syntax      : ansible-playbook crt_spongebob.yml  -e "vmname=SpongeBobVM1"
# Description : 
##############################################################################
---
##################################################################
# create configuration for vm 
##################################################################
- name: Create Azure VM
  hosts: localhost
  become_method: sudo
  become: yes
  remote_user: pcp
  connection: local
  tasks:
    - include_vars: resource-info-conf.yml
    - include_tasks: crt_spongebob_conf.yml
    - name: "Create VM by inventory file" 
      include_tasks: crt_spongebob_vm.yml 
      loop: "{{ query('inventory_hostnames', '{{ vmname }}') }}"
      loop_control:
        loop_var: item_vm

##################################################################
# create vm with disk 
##################################################################
- name: Create Volume Group on Azure VM
  hosts: "{{ vmname }}"
  become_method: sudo
  become: yes
  remote_user: pcp
  tasks:
    - include_vars: resource-info-vol.yml
    - name: "Create Logical Volumon on VM"
      include_tasks: crt_spongebob_vol.yml

##################################################################
# make up vm : volume, selinux, firewalld, ntp ... 
##################################################################
- name: Make up Azure VM
  hosts: "{{ vmname }}"
  become_method: sudo
  become: yes
  remote_user: pcp
  tasks:
    - name: "Create Logical Volumon on VM"
      include_tasks: crt_spongebob_mku.yml
