##################################################################
# Name        : crt_spongebob_conf.yml
# Creator     : L.S.H.
# Syntax      : None 
# Description : Be included from crt_spongebob.yml
##################################################################
---
- name: Create resource group
  azure_rm_resourcegroup:
    name: "{{ ResourceGroup }}"
    location: "{{ Location }}"

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ ResourceGroup }}"
    name: "{{ Vnet }}"
    address_prefixes: "10.0.0.0/16"

- name: Add subnet
  azure_rm_subnet:
    resource_group: "{{ ResourceGroup }}"
    name: "{{ Subnet }}"
    address_prefix: "10.0.1.0/24"
    virtual_network: "{{ Vnet }}"

- name: Create Network Security Group that allows SSH
  azure_rm_securitygroup:
    resource_group: "{{ ResourceGroup }}"
    name: "{{ NetworkSecurityGroup }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
