- name: create dataroaster user
  user:
    name: dataroaster
    state: present
    createhome: yes
    home: "{{ dataroaster_home_dir }}"
  become: true


- name: create dataroaster directories
  file:
    path: "{{ item }}"
    state: directory
    owner: dataroaster
    group: dataroaster
    mode: 0755
  with_items:
    - "{{ dataroaster_home_dir }}"
    - "{{ authorizer_home_dir }}"
    - "{{ dataroaster_log_dir }}"
  become: true


- name: download and extract authorizer distribution
  shell: "{{ item }}"
  args:
    executable: /bin/bash
    chdir: "{{ authorizer_home_dir }}"
  with_items:
    - "wget https://github.com/cloudcheflabs/dataroaster/releases/download/{{ dataroaster_version }}/authorizer-{{ dataroaster_version }}-dist.tgz"
    - "tar zxvf authorizer-*-dist.tgz"
    - "cp -R authorizer/* ."
    - "rm -rf authorizer-*-dist.tgz"
    - "rm -rf authorizer/"
  become: dataroaster

- name: copy authorizer configuration
  template:
    src: "templates/{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: dataroaster
    group: dataroaster
    mode: 0755
  with_items:
    - { src: 'application-prod.yml', dest: '{{ authorizer_home_dir }}/conf/application-prod.yml' }
    - { src: 'logback.xml', dest: '{{ authorizer_home_dir }}/logback.xml' }


- name: start authorizer
  shell: "{{ item }}"
  args:
    executable: /bin/bash
    chdir: "{{ authorizer_home_dir }}"
  with_items:
    - "./start-authorizer.sh"
  become: dataroaster
