#########################################################################
# Name        : crt_spongebob_mku.yml
# Creator     : L.S.H.
# Syntax      : None, just be called by main playbook 
# Description : Make up VM on Azure & Be included from crt_spongebob.yml
#########################################################################
---
####################################
# hostname change 
####################################
- name: "Change host name"
  hostname:
    name: "{{ inventory_hostname_short }}"

####################################
# ntp/jdk install 
####################################
- name: "ntp, jdk install"
  yum:
    name: 
      - ntp
      - java-1.8.0-openjdk
    state: latest


####################################
# ntp setup
####################################
- name: "Set ntp.conf"
  template:
    src: /etc/ansible/template/ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644

- name: "regist auto start"
  service:
    name: ntpd
    enabled: yes

- name: start ntp
  service:
    name: ntpd
    state: restarted

####################################
# timezone setup
####################################
- name: "TimeZone setup"
  timezone:
    name: Asia/Seoul
    
####################################
# selinux disable
####################################
- name: Disable SELinux
  selinux:
    state: disabled

####################################
# firewalld disable
####################################
- name: Disable firesalld
  service:
    name: firewalld
    state: stopped
    enabled: False

####################################
# swap disable
####################################
- name: Disable swap
  shell: |
    sudo sed -i '/swap/d' /etc/fstab
    sudo swapoff -a

####################################
# Copy the ssh key to node 
####################################
- name: Copy the key add to authorized_keys using Ansible module
  authorized_key:
    user: "{{ user }}" 
    state: present
    key: "{{ lookup('file','/home/{{ user }}/.ssh/id_rsa.pub')}}"

####################################
# Ansible install on master  
# Host information add 
####################################
#- name: "EPEL Repository add" 
#  yum_repository:
#    name: epel
#    description: EPEL YUM repo
#    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
#    gpgcheck: no
#  when: "AnsibleSvr in inventory_hostname"
#
#- name: "Ansible install"
#  yum:
#    name: 
#      - ansible
#    state: latest
#  when: "AnsibleSvr in inventory_hostname"
#
#- name: "   1) Copy file with owner and permissions"
#  copy:
#    src: /etc/ansible/template/hosts
#    dest: /tmp/hosts
#    owner: root
#    group: root
#    mode: '0644'
#    force: yes
#  when: "AnsibleSvr in inventory_hostname"
#
#- name: "   2) get remote file contents"
#  slurp:
#    src: /tmp/hosts
#  register: hostsinfo
#  when: "AnsibleSvr in inventory_hostname"
#
#- name: "   3) insert hosts file contents"
#  blockinfile:
#    block: "{{ hostsinfo['content'] | b64decode }}"
#    dest: /etc/hosts
#    backup: no
#    marker: ""
#    insertafter: EOF
#  when: "AnsibleSvr in inventory_hostname"
#
#- name: "   4) Remove blank lines"
#  lineinfile :
#    path: /etc/hosts
#    state: absent
#    regexp: '^$'
#  when: "AnsibleSvr in inventory_hostname"
