##############################################################################
# Name        : crt_spongebob.yml
# Creator     : L.S.H.
# Syntax      : ansible-playbook crt_spongebob.yml  -e "vmname=SpongeBobVM1"
# Description : 
##############################################################################
---
##################################################################
# 1. create configuration for vm 
##################################################################
- name: Create Azure VM
  hosts: localhost
  become_method: sudo
  become: yes
  remote_user: pcp
  connection: local
  tasks:
    - include_vars: resource-info-conf.yml
    - include_tasks: crt_spongebob_conf.yml
    - name: "Create VM by inventory file" 
      vars: 
        NicNM: "{{ NIC }}_{{ item_vm }}"
      include_tasks: crt_spongebob_vm.yml 
      loop: "{{ query('inventory_hostnames', '{{ vmname }}') }}"
      loop_control:
        loop_var: item_vm

##################################################################
# 2. create vm with disk 
##################################################################
- name: Create Volume Group on Azure VM
  hosts: "{{ vmname }}"
  become_method: sudo
  become: yes
  remote_user: pcp
  tasks:
    - include_vars: resource-info-vol.yml
    - name: "Create Logical Volumon on VM"
      include_tasks: crt_spongebob_vol.yml

##################################################################
# 3. make up vm : selinux, firewalld, ntp, jdk  ... 
##################################################################
- name: Make up Azure VM
  hosts: "{{ vmname }}"
  become_method: sudo
  become: yes
  remote_user: pcp
  tasks:
    - include_vars: resource-info-conf.yml

    - name: "Make up Ansible VM" 
      include_tasks: crt_spongebob_ans.yml
      when: "AnsibleSvr in inventory_hostname"

    - name: "Make up VM"
      include_tasks: crt_spongebob_mku.yml


