###########################################################################
# Name        : mgmt_vm_start.yml
# Creator     : L.S.H.
# Syntax      : ansible-playbook mgmt_vm_start.yml -e "vmname=SpongeBobVM1"
#               Start : 
# Description :
###########################################################################
---
- name: Create Azure VM
  hosts: localhost
  become: yes
  connection: local
  tasks:
    - include_vars: resource-info-conf.yml
    - name: "Start virtual machine"
      azure_rm_virtualmachine:
        resource_group: "{{ ResourceGroup }}"
        name: "{{ item_vm }}"
      loop: "{{ query('inventory_hostnames', '{{ vmname }}') }}"
      loop_control:
        loop_var: item_vm
