- hosts: "{{ target_hosts }}"
  remote_user: "{{ exec_user }}"
  become: true

  vars:
  - ansible_ssh_user: "{{ exec_user }}"

  roles:
    - role: "mysql/stop"
    - role: "mysql/start"
    - role: "vault/stop"
    - role: "vault/start"
    - role: "authorizer/stop"
    - role: "authorizer/start"
    - role: "apiserver/stop"
    - role: "apiserver/start"

