nodes:
  - address: 52.141.62.98
    internal_address: 10.0.2.4
    hostname_override: maya-0
    user: pcp
    role:
      - controlplane
      - etcd
      - worker
    ssh_key: |-
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpQIBAAKCAQEA0LPbSPlganymAgCOWMSskjz5nUsnUbnD/onbH/Y/SJOFq2UA
      3tSlj6M1WWFwp8669oZwZII/kLhyeyN4Hr3cKUzsInL5HwK4CRuro7XS/Qx8dxtE
      hgPSALzTE2lxY9/u39w7ESAdv5k96JkxanfyFauRX7U0LrhUZJA4MsSvH62quJVT
      hGi1vw9Y4j8U33pL7FIDpua+8Jw86C5SJw+YnoM1lVAspDSdS8o7sTvdQQLYmVhS
      zyImmEYdK69xM1EdWr7YutWXtquUNoy3d6UEhgKB4jbMEH/eY9PJtD7WmyxKX+Ye
      Rqpyih5qVyJ+zl3U2Y/OTSPqjJnFno/8knsiRwIDAQABAoIBAQCaRRjHLG90x4b+
      2+JdA6R8xM3O04rRAnw6XzS2v5Ov1jxsoVCvZoirUH1TAJABuvLA4EecRBswoucc
      1u8n6jgf31h9bndv0NaxBN8vOGwp2Vz3vhQ86/4DxZBRPRQwO4ubtnODCTZ0NpZo
      pTS9+sPb+OKQ2KUmE+NuIp0oCfNZefNSeX9XrTWsdMzTwFBv+5iOZwWCHAZGjc8o
      j5M+Ns3oOwen9KAuxEwtJjOciKGlLTj1QOcQaSA8oVqoGwjKIcORgAYJ4lerOGdU
      ew5KPzgnr4gy/Nka939vbqrw5D2cK/ndpyn1FugCOpHBB/d3xazO+T0cyDfuNfEV
      EqztYLvBAoGBAPuJUVQKKzUgsonTzdszU91FTQkyxfZyij07hVZsX5lUDz8PYEE2
      wKV8/wjgXjSwTIQdNxUSoWJ4jxn98K7rXJ7xQ7PNkvho7K5L8GACPU4PilOcy9lF
      /J634C7wuyIvlcJ2/gZ0k7SsyYqj3ve8rrcxFkfRPd5drK72FYs3oDA/AoGBANRn
      8/CBd2mySExhK21fvJ0PfBchtCH/WUQw0gNJgT1gr1xe2hVjqeVpBhWcMGwvp0TE
      My97hjzE62q0Nwc/YXiqm9jMqeofjyfMXvwtvW9caH9CB7ofH8hauqAn/J72lPS3
      95bQtdcTc6v0/kcLRfPCcTe8JokIEJ/5esqkBov5AoGBAN+HqD6Gyt7rr73L+6RQ
      eLaqX0tNU58vKqo/ur6SkGIx0Vq4z1Ek1w45hmrc+NrZ0SWW0NxpMgHQIVt3z+ui
      PS0COqgOiA05MRuzYGnxk4lLRiIHtR/gkh56ST9trt8yamPmWthhwOFOq8wI1JxT
      kPA7LxGjYNe7ZzoUdhDB3hkBAoGATxwcjfIaYKKHLPNv8j+bB0BSLmdeKN9rBuvL
      /G9vFEYjahrlzNue1pPkMT5IBrNE8GbGzaOLHq0VJVvTtv5TNlcMzpWDn3B7qA4F
      PpVmnchkHymfqSGYe83W/nmGLEqYtgCi1WgMoftbtKr93cYEGsLL2j9YducrEfog
      UsL+sTkCgYEA9znxqAdpFf4+zfi84NyfPuurxQzDwPU6tMDSN67FEFZCydXyjZjH
      TWaVks8eQDYPkhx+9OC6WTkLSXL2lutEIWnJk8UZ0amuJfCWtQvl7mOozhEM6EUJ
      1VfrYXWZYwVD6bfnYsYXuo1TbIC/3K3icUhfs/TymJkKfv30mIcScLI=
      -----END RSA PRIVATE KEY-----
    port: 22
  - address: 52.141.63.222
    internal_address: 10.0.2.5
    hostname_override: maya-1
    user: pcp
    role:
      - controlplane
      - etcd
      - worker
    ssh_key: |-
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpQIBAAKCAQEA0LPbSPlganymAgCOWMSskjz5nUsnUbnD/onbH/Y/SJOFq2UA
      3tSlj6M1WWFwp8669oZwZII/kLhyeyN4Hr3cKUzsInL5HwK4CRuro7XS/Qx8dxtE
      hgPSALzTE2lxY9/u39w7ESAdv5k96JkxanfyFauRX7U0LrhUZJA4MsSvH62quJVT
      hGi1vw9Y4j8U33pL7FIDpua+8Jw86C5SJw+YnoM1lVAspDSdS8o7sTvdQQLYmVhS
      zyImmEYdK69xM1EdWr7YutWXtquUNoy3d6UEhgKB4jbMEH/eY9PJtD7WmyxKX+Ye
      Rqpyih5qVyJ+zl3U2Y/OTSPqjJnFno/8knsiRwIDAQABAoIBAQCaRRjHLG90x4b+
      2+JdA6R8xM3O04rRAnw6XzS2v5Ov1jxsoVCvZoirUH1TAJABuvLA4EecRBswoucc
      1u8n6jgf31h9bndv0NaxBN8vOGwp2Vz3vhQ86/4DxZBRPRQwO4ubtnODCTZ0NpZo
      pTS9+sPb+OKQ2KUmE+NuIp0oCfNZefNSeX9XrTWsdMzTwFBv+5iOZwWCHAZGjc8o
      j5M+Ns3oOwen9KAuxEwtJjOciKGlLTj1QOcQaSA8oVqoGwjKIcORgAYJ4lerOGdU
      ew5KPzgnr4gy/Nka939vbqrw5D2cK/ndpyn1FugCOpHBB/d3xazO+T0cyDfuNfEV
      EqztYLvBAoGBAPuJUVQKKzUgsonTzdszU91FTQkyxfZyij07hVZsX5lUDz8PYEE2
      wKV8/wjgXjSwTIQdNxUSoWJ4jxn98K7rXJ7xQ7PNkvho7K5L8GACPU4PilOcy9lF
      /J634C7wuyIvlcJ2/gZ0k7SsyYqj3ve8rrcxFkfRPd5drK72FYs3oDA/AoGBANRn
      8/CBd2mySExhK21fvJ0PfBchtCH/WUQw0gNJgT1gr1xe2hVjqeVpBhWcMGwvp0TE
      My97hjzE62q0Nwc/YXiqm9jMqeofjyfMXvwtvW9caH9CB7ofH8hauqAn/J72lPS3
      95bQtdcTc6v0/kcLRfPCcTe8JokIEJ/5esqkBov5AoGBAN+HqD6Gyt7rr73L+6RQ
      eLaqX0tNU58vKqo/ur6SkGIx0Vq4z1Ek1w45hmrc+NrZ0SWW0NxpMgHQIVt3z+ui
      PS0COqgOiA05MRuzYGnxk4lLRiIHtR/gkh56ST9trt8yamPmWthhwOFOq8wI1JxT
      kPA7LxGjYNe7ZzoUdhDB3hkBAoGATxwcjfIaYKKHLPNv8j+bB0BSLmdeKN9rBuvL
      /G9vFEYjahrlzNue1pPkMT5IBrNE8GbGzaOLHq0VJVvTtv5TNlcMzpWDn3B7qA4F
      PpVmnchkHymfqSGYe83W/nmGLEqYtgCi1WgMoftbtKr93cYEGsLL2j9YducrEfog
      UsL+sTkCgYEA9znxqAdpFf4+zfi84NyfPuurxQzDwPU6tMDSN67FEFZCydXyjZjH
      TWaVks8eQDYPkhx+9OC6WTkLSXL2lutEIWnJk8UZ0amuJfCWtQvl7mOozhEM6EUJ
      1VfrYXWZYwVD6bfnYsYXuo1TbIC/3K3icUhfs/TymJkKfv30mIcScLI=
      -----END RSA PRIVATE KEY-----
    port: 22
  - address: 52.231.38.217
    internal_address: 10.0.2.6
    hostname_override: maya-2
    user: pcp
    role:
      - controlplane
      - etcd
      - worker
    ssh_key: |-
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpQIBAAKCAQEA0LPbSPlganymAgCOWMSskjz5nUsnUbnD/onbH/Y/SJOFq2UA
      3tSlj6M1WWFwp8669oZwZII/kLhyeyN4Hr3cKUzsInL5HwK4CRuro7XS/Qx8dxtE
      hgPSALzTE2lxY9/u39w7ESAdv5k96JkxanfyFauRX7U0LrhUZJA4MsSvH62quJVT
      hGi1vw9Y4j8U33pL7FIDpua+8Jw86C5SJw+YnoM1lVAspDSdS8o7sTvdQQLYmVhS
      zyImmEYdK69xM1EdWr7YutWXtquUNoy3d6UEhgKB4jbMEH/eY9PJtD7WmyxKX+Ye
      Rqpyih5qVyJ+zl3U2Y/OTSPqjJnFno/8knsiRwIDAQABAoIBAQCaRRjHLG90x4b+
      2+JdA6R8xM3O04rRAnw6XzS2v5Ov1jxsoVCvZoirUH1TAJABuvLA4EecRBswoucc
      1u8n6jgf31h9bndv0NaxBN8vOGwp2Vz3vhQ86/4DxZBRPRQwO4ubtnODCTZ0NpZo
      pTS9+sPb+OKQ2KUmE+NuIp0oCfNZefNSeX9XrTWsdMzTwFBv+5iOZwWCHAZGjc8o
      j5M+Ns3oOwen9KAuxEwtJjOciKGlLTj1QOcQaSA8oVqoGwjKIcORgAYJ4lerOGdU
      ew5KPzgnr4gy/Nka939vbqrw5D2cK/ndpyn1FugCOpHBB/d3xazO+T0cyDfuNfEV
      EqztYLvBAoGBAPuJUVQKKzUgsonTzdszU91FTQkyxfZyij07hVZsX5lUDz8PYEE2
      wKV8/wjgXjSwTIQdNxUSoWJ4jxn98K7rXJ7xQ7PNkvho7K5L8GACPU4PilOcy9lF
      /J634C7wuyIvlcJ2/gZ0k7SsyYqj3ve8rrcxFkfRPd5drK72FYs3oDA/AoGBANRn
      8/CBd2mySExhK21fvJ0PfBchtCH/WUQw0gNJgT1gr1xe2hVjqeVpBhWcMGwvp0TE
      My97hjzE62q0Nwc/YXiqm9jMqeofjyfMXvwtvW9caH9CB7ofH8hauqAn/J72lPS3
      95bQtdcTc6v0/kcLRfPCcTe8JokIEJ/5esqkBov5AoGBAN+HqD6Gyt7rr73L+6RQ
      eLaqX0tNU58vKqo/ur6SkGIx0Vq4z1Ek1w45hmrc+NrZ0SWW0NxpMgHQIVt3z+ui
      PS0COqgOiA05MRuzYGnxk4lLRiIHtR/gkh56ST9trt8yamPmWthhwOFOq8wI1JxT
      kPA7LxGjYNe7ZzoUdhDB3hkBAoGATxwcjfIaYKKHLPNv8j+bB0BSLmdeKN9rBuvL
      /G9vFEYjahrlzNue1pPkMT5IBrNE8GbGzaOLHq0VJVvTtv5TNlcMzpWDn3B7qA4F
      PpVmnchkHymfqSGYe83W/nmGLEqYtgCi1WgMoftbtKr93cYEGsLL2j9YducrEfog
      UsL+sTkCgYEA9znxqAdpFf4+zfi84NyfPuurxQzDwPU6tMDSN67FEFZCydXyjZjH
      TWaVks8eQDYPkhx+9OC6WTkLSXL2lutEIWnJk8UZ0amuJfCWtQvl7mOozhEM6EUJ
      1VfrYXWZYwVD6bfnYsYXuo1TbIC/3K3icUhfs/TymJkKfv30mIcScLI=
      -----END RSA PRIVATE KEY-----
    port: 22


cloud_provider:
  name: azure
  azureCloudProvider:
    aadClientId: 39f72fe1-7136-480e-ae01-f144e031702f
    aadClientSecret: icarus
    resourceGroup: openebs
    subscriptionId: d87fad0a-1906-46a7-814a-a17e15427903
    tenantId: 7414e334-a9c3-46a2-8db5-7b59083b240f

# If set to true, RKE will not fail when unsupported Docker version
# are found
ignore_docker_version: false

# Cluster level SSH private key
# Used if no ssh information is set for the node
ssh_key_path: ~/.ssh/id_rsa

# Enable use of SSH agent to use SSH private keys with passphrase
# This requires the environment `SSH_AUTH_SOCK` configured pointing
#to your SSH agent which has the private key added
ssh_agent_auth: true

# List of registry credentials
# If you are using a Docker Hub registry, you can omit the `url`
# or set it to `docker.io`
# is_default set to `true` will override the system default
# registry set in the global settings
#private_registries:
#  - url: registry.com
#    user: Username
#    password: password
#    is_default: true

# Bastion/Jump host configuration
#bastion_host:
#  address: x.x.x.x
#  user: ubuntu
#  port: 22
#  ssh_key_path: /home/user/.ssh/bastion_rsa
# or
#   ssh_key: |-
#     -----BEGIN RSA PRIVATE KEY-----
#
#     -----END RSA PRIVATE KEY-----

# Set the name of the Kubernetes cluster
cluster_name: cluster.local


# The Kubernetes version used. The default versions of Kubernetes
# are tied to specific versions of the system images.
#
# For RKE v0.2.x and below, the map of Kubernetes versions and their system images is
# located here:
# https://github.com/rancher/types/blob/release/v2.2/apis/management.cattle.io/v3/k8s_defaults.go
#
# For RKE v0.3.0 and above, the map of Kubernetes versions and their system images is
# located here:
# https://github.com/rancher/kontainer-driver-metadata/blob/master/rke/k8s_rke_system_images.go
#
# In case the kubernetes_version and kubernetes image in
# system_images are defined, the system_images configuration
# will take precedence over kubernetes_version.
kubernetes_version: v1.17.6-rancher2-2

# System Images are defaulted to a tag that is mapped to a specific
# Kubernetes Version and not required in a cluster.yml.
# Each individual system image can be specified if you want to use a different tag.
#
# For RKE v0.2.x and below, the map of Kubernetes versions and their system images is
# located here:
# https://github.com/rancher/types/blob/release/v2.2/apis/management.cattle.io/v3/k8s_defaults.go
#
# For RKE v0.3.0 and above, the map of Kubernetes versions and their system images is
# located here:
# https://github.com/rancher/kontainer-driver-metadata/blob/master/rke/k8s_rke_system_images.go
#
#system_images:
#  kubernetes: rancher/hyperkube:v1.10.3-rancher2
#  etcd: rancher/coreos-etcd:v3.1.12
#  alpine: rancher/rke-tools:v0.1.9
#  nginx_proxy: rancher/rke-tools:v0.1.9
#  cert_downloader: rancher/rke-tools:v0.1.9
#  kubernetes_services_sidecar: rancher/rke-tools:v0.1.9
#  kubedns: rancher/k8s-dns-kube-dns-amd64:1.14.8
#  dnsmasq: rancher/k8s-dns-dnsmasq-nanny-amd64:1.14.8
#  kubedns_sidecar: rancher/k8s-dns-sidecar-amd64:1.14.8
#  kubedns_autoscaler: rancher/cluster-proportional-autoscaler-amd64:1.0.0
#  pod_infra_container: rancher/pause-amd64:3.1

services:
  etcd:
  # if external etcd is used
  # path: /etcdcluster
  # external_urls:
  #   - https://etcd-example.com:2379
  # ca_cert: |-
  #   -----BEGIN CERTIFICATE-----
  #   xxxxxxxxxx
  #   -----END CERTIFICATE-----
  # cert: |-
  #   -----BEGIN CERTIFICATE-----
  #   xxxxxxxxxx
  #   -----END CERTIFICATE-----
  # key: |-
  #   -----BEGIN PRIVATE KEY-----
  #   xxxxxxxxxx
  #   -----END PRIVATE KEY-----
  # Note for Rancher v2.0.5 and v2.0.6 users: If you are configuring
  # Cluster Options using a Config File when creating Rancher Launched
  # Kubernetes, the names of services should contain underscores
  # only: `kube_api`.
  kube-api:
    # IP range for any services created on Kubernetes
    # This must match the service_cluster_ip_range in kube-controller
    service_cluster_ip_range: 10.233.0.0/18
    # Expose a different port range for NodePort services
    service_node_port_range: 30000-32767
    pod_security_policy: false
    # Add additional arguments to the kubernetes API server
    # This WILL OVERRIDE any existing defaults
    extra_args:
      # Enable audit log to stdout
      audit-log-path: "-"
      # Increase number of delete workers
      delete-collection-workers: 3
      # Set the level of log output to debug-level
      v: 4
  # Note for Rancher 2 users: If you are configuring Cluster Options
  # using a Config File when creating Rancher Launched Kubernetes,
  # the names of services should contain underscores only:
  # `kube_controller`. This only applies to Rancher v2.0.5 and v2.0.6.
  kube-controller:
    # CIDR pool used to assign IP addresses to pods in the cluster
    cluster_cidr: 10.233.64.0/18
    # IP range for any services created on Kubernetes
    # This must match the service_cluster_ip_range in kube-api
    service_cluster_ip_range: 10.233.0.0/18
  kubelet:
    # Base domain for the cluster
    cluster_domain: cluster.local
    # IP address for the DNS service endpoint
    cluster_dns_server: 10.233.0.10
    # Fail if swap is on
    fail_swap_on: false
    # Set max pods to 250 instead of default 110
    extra_args:
      max-pods: 250
    # Optionally define additional volume binds to a service
    extra_binds:
      - "/usr/libexec/kubernetes/kubelet-plugins:/usr/libexec/kubernetes/kubelet-plugins"
  kubeproxy:
    extra_args:
      proxy-mode: iptables

# Currently, only authentication strategy supported is x509.
# You can optionally create additional SANs (hostnames or IPs) to
# add to the API server PKI certificate.
# This is useful if you want to use a load balancer for the
# control plane servers.
#authentication:
#  strategy: x509
#  sans:
#    - "10.18.160.10"
#    - "my-loadbalancer-1234567890.us-west-2.elb.amazonaws.com"

# Kubernetes Authorization mode
# Use `mode: rbac` to enable RBAC
# Use `mode: none` to disable authorization
authorization:
  mode: rbac

# If you want to set a Kubernetes cloud provider, you specify
# the name and configuration
#cloud_provider:
#  name: aws

# Add-ons are deployed using kubernetes jobs. RKE will give
# up on trying to get the job status after this timeout in seconds..
addon_job_timeout: 30

# Specify network plugin-in (canal, calico, flannel, weave, or none)
network:
  plugin: canal

# Specify DNS provider (coredns or kube-dns)
dns:
  provider: coredns

# Currently only nginx ingress provider is supported.
# To disable ingress controller, set `provider: none`
# `node_selector` controls ingress placement and is optional
ingress:
  provider: none

# All add-on manifests MUST specify a namespace
#addons: |-
#  ---
#  apiVersion: v1
#  kind: Pod
#  metadata:
#    name: my-nginx
#    namespace: default
#  spec:
#    containers:
#    - name: my-nginx
#      image: nginx
#      ports:
#      - containerPort: 80
#
#addons_include:
#  - https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/rook-operator.yaml
#  - https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/rook-cluster.yaml
#  - /path/to/manifest
#  EDIT THIS PAGE