---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: {{ namespace }}
type: Opaque
data:
  ROOT_PASSWORD: aWNhcnVzMDMzNw==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: {{ namespace }}
  labels:
    app: mysql
spec:
  strategy:
    type: Recreate
  serviceName: mysql-service
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              subPath: "mysql"
              name: mysql-data
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: ROOT_PASSWORD
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ storageSize }}Gi
        storageClassName: {{ storageClass }}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: {{ namespace }}
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306