kind: Service
apiVersion: v1
metadata:
  name: minio-service
  namespace: minio
  labels:
    app: minio-service
spec:
  type: ClusterIP
  selector:
    app: minio
  ports:
    - name: minio
      port: 9099
      targetPort: 9000

---
kind: Service
apiVersion: v1
metadata:
  name: minio
  namespace: minio
  labels:
    app: minio
spec:
  clusterIP: None
  selector:
    app: minio
  ports:
    - name: minio
      port: 9000
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: minio
  labels:
    app: minio
spec:
  serviceName: minio
  replicas: 16
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2020-09-05T07-14-49Z
          env:
            - name: MINIO_ACCESS_KEY
              value: bWluaW8=
            - name: MINIO_SECRET_KEY
              value: bWluaW8xMjM=
          volumeMounts:
            - name: minio-data-1
              mountPath: /data1
            - name: minio-data-2
              mountPath: /data2
            - name: minio-data-3
              mountPath: /data3
            - name: minio-data-4
              mountPath: /data4
          args:
            - "server"
            - "http://minio-{1...4}.minio.minio.svc.cluster.local:9000/data{1...4}"
  volumeClaimTemplates: # This is the specification in which you reference the StorageClass
    - metadata:
        name: minio-data-1
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Gi
        storageClassName: direct.csi.min.io # This field references the existing StorageClass
    - metadata:
        name: minio-data-2
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Gi
        storageClassName: direct.csi.min.io # This field references the existing StorageClass
    - metadata:
        name: minio-data-3
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Gi
        storageClassName: direct.csi.min.io # This field references the existing StorageClass
    - metadata:
        name: minio-data-4
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Gi
        storageClassName: direct.csi.min.io # This field references the existing StorageClass
