apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: {{ namespace }}
spec:
  version: 7.9.1
  count: 1
  config:
    telemetry.enabled: false
  elasticsearchRef:
    name: {{ esClusterName }}
    namespace: {{ namespace }}
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        type: LoadBalancer