- name: uninstall jdk
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - "java-1.8.0-openjdk"
    - "java-1.8.0-openjdk-devel"
  become: true

- name: uninstall maven
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - "maven"
  become: true

- name: uninstall kubectl
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - "kubectl"
  become: true

- name: uninstall helm
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/usr/local/bin/helm"