- name: install jdk
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "java-1.8.0-openjdk"
    - "java-1.8.0-openjdk-devel"
  become: true

- name: copy repo file
  template:
    src: "templates/{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}"
    mode: 0755
  with_items:
    - "kubernetes.repo"

- name: install kubectl
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "kubectl"
  become: true

- name: create temp directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ prerequisite_helm_temp_dir }}"

- name: install helm
  shell: "{{ item }}"
  args:
    executable: /bin/bash
    chdir: "{{ prerequisite_helm_temp_dir }}"
  with_items:
    - "curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3"
    - "chmod 700 get_helm.sh"
    - "./get_helm.sh"
  become: true

- name: remove temp dir
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ prerequisite_helm_temp_dir }}"