- name: install jdk
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "java-1.8.0-openjdk"
    - "java-1.8.0-openjdk-devel"
  become: true

- name: copy repo file
  template:
    src: "templates/{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}"
    mode: 0755
  with_items:
    - "kubernetes.repo"

- name: install kubectl
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "kubectl"
  become: true

- name: create temp directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ prerequisite_helm_temp_dir }}"

- name: install helm
  shell: "{{ item }}"
  args:
    executable: /bin/bash
    chdir: "{{ prerequisite_helm_temp_dir }}"
  with_items:
    - "wget https://get.helm.sh/helm-v{{ prerequisite_helm_version }}-linux-amd64.tar.gz"
    - "tar zxvf helm-v{{ prerequisite_helm_version }}-linux-amd64.tar.gz"
    - "cp linux-amd64/helm /usr/local/bin/helm"
  become: true

- name: remove temp dir
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ prerequisite_helm_temp_dir }}"