server:
  port: 8082
  servlet:
    context-path: /api

authorizer:
  url: http://localhost:8091

client:
  secret: YXBpOmhlbGxvQXV0aEFQSQ==

vault:
  host: localhost
  port: 8200
  trustStore: /home/pcp/vault/work/keystore.jks
  token: s.pUhTmVSVibeasA9eMlNfXVk1

objectStorage:
  minio:
    defaultAccessKey: bWluaW8=
    defaultSecretKey: bWluaW8xMjM=